name: CI build

on:
  push:
    branches: [ master, test_action ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    timeout-minutes: 3
    env:
      TERM: xterm

    steps:
    - uses: actions/checkout@v2
    - name: show OS info
      run: cat /etc/os-release
    - name: install dependencies
      run: |
        sudo apt-get -qq update
        sudo apt-get install -y libhamlib-dev libxmlrpc-core-c3-dev libcmocka-dev     
    - name: autoreconf and basic make
      run: autoreconf -i && ./configure && make -j2
    - name: configure with xmlrpc
      run: make clean && ./configure --enable-fldigi-xmlrpc && make -j2
    - name: run tests
      run: TERM=xterm make check; rc=$?; cat test/run_*.log; exit $rc
    - name: Color
      run: echo TERM is; tput bold; tput setaf 1;echo $TERM; tput sgr0
