name: CI build for Ubuntu 20

on:
  push:
    branches: [ master, poc_test_rules ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-20.04
    timeout-minutes: 3
    env:
      TERM: xterm
      AM_COLOR_TESTS: always

    steps:
    - uses: actions/checkout@v3
    - name: Show OS info
      run: cat /etc/os-release
    - name: Install dependencies
      run: |
        sudo apt-get -qq update
        sudo apt-get install -y libhamlib-dev libxmlrpc-core-c3-dev libcmocka-dev     
    - name: Autoreconf and basic make
      run: autoreconf -i && ./configure && make -j2
    - name: Configure with xmlrpc
      run: make clean && ./configure --enable-fldigi-xmlrpc && make -j2
    - name: Run tests
      id: run_tests
      continue-on-error: true
      run: make check
    - name: Tests failed
      if: ${{ steps.run_tests.outcome == 'failure' }}
      run: cat test/run_*.log && find test/rules/ -ls && exit 1
